import path from 'node:path';
import { fileURLToPath } from 'node:url';

const __filename = fileURLToPath(import.meta.url);
const __dirname = path.dirname(__filename);

// Define aliases for module paths
export const aliases = {
	$: path.resolve(__dirname, './src'),
	$src: path.resolve(__dirname, './src'),
	$layouts: path.resolve(__dirname, './src/layouts'),
	$pages: path.resolve(__dirname, './src/pages'),
	$assets: path.resolve(__dirname, './src/lib/assets'),
	$styles: path.resolve(__dirname, './src/lib/styles'),
	$components: path.resolve(__dirname, './src/lib/components'),
	$solid: path.resolve(__dirname, './src/components/solid'),
	$react: path.resolve(__dirname, './src/components/react'),
	$vue: path.resolve(__dirname, './src/components/vue'),
	$stores: path.resolve(__dirname, './src/lib/stores'),
	$contexts: path.resolve(__dirname, './src/lib/contexts'),
	$utils: path.resolve(__dirname, './src/lib/utils'),
	$paraglide: path.resolve(__dirname, './src/lib/paraglide'),
	$i18n: path.resolve(__dirname, './src/lib/i18n'),
	$html: path.resolve(__dirname, './src/html'),
	$static: path.resolve(__dirname, './static'),
	$output: path.resolve(__dirname, './output'),
	$images: path.resolve(__dirname, './public/images'),
	$events: path.resolve(__dirname, './events'),
	'@/src': path.resolve(__dirname, './src'),
	'@/lib': path.resolve(__dirname, './src/lib'),
	'@/layouts': path.resolve(__dirname, './src/layouts'),
	'@/pages': path.resolve(__dirname, './src/pages'),
	'@/data': path.resolve(__dirname, './src/lib/data'),
	'@/styles': path.resolve(__dirname, './src/lib/styles'),
	'@/components': path.resolve(__dirname, './src/lib/components'),
	'@/components/solid': path.resolve(__dirname, './src/components/solid'),
	'@/components/react': path.resolve(__dirname, './src/components/react'),
	'@/components/vue': path.resolve(__dirname, './src/components/vue'),
	'@/stores': path.resolve(__dirname, './src/lib/stores'),
	'@/contexts': path.resolve(__dirname, './src/lib/contexts'),
	'@/utils': path.resolve(__dirname, './src/lib/utils'),
	'@/i18n': path.resolve(__dirname, './src/lib/i18n'),
	'@/paraglide': path.resolve(__dirname, './src/lib/paraglide'),
	'@/html': path.resolve(__dirname, './src/lib/html'),
	'@/static': path.resolve(__dirname, './static'),
	'@/output': path.resolve(__dirname, './output'),
	'@/images': path.resolve(__dirname, './public/images'),
	'@/events': path.resolve(__dirname, './events'),
	'@/mocks': path.resolve(__dirname, './src/lib/mocks'),
	'@/types': path.resolve(__dirname, './src/lib/types'),
};
