export let categories = [
	{
		id: 29,
		name: {
			ko: '행사부스',
			en: 'Event booth',
			zh: '活动展位',
			ja: 'イベントブース',
			th: 'บูธกิจกรรม',
			vi: 'Gian hàng sự kiện',
		},
		iconKey: 'popper',
		sortingNumber: 1,
		isEventCategory: true,
		isAiRecommendationEnabled: false,
		categoryColorCodes: {
			id: 5,
			paletteNumber: 5,
			sortingNumber: 5,
			colorCode: '#23B63C',
		},
		_count: {
			facilities: 27,
		},
	},
	{
		id: 21,
		name: {
			ko: '무장애',
			en: 'Barrier-free',
			zh: '无障碍',
			ja: 'バリアフリー',
			th: 'ไร้สิ่งกีดขวาง',
			vi: 'Không có rào cản',
		},
		iconKey: 'wheelchair',
		sortingNumber: 2,
		isEventCategory: true,
		isAiRecommendationEnabled: true,
		categoryColorCodes: {
			id: 9,
			paletteNumber: 9,
			sortingNumber: 9,
			colorCode: '#BA66EF',
		},
		_count: {
			facilities: 0,
		},
	},
	{
		id: 19,
		name: {
			ko: '포토존',
			en: 'Photo zone',
			zh: '摄影区',
			ja: 'フォトゾーン',
			th: 'โซนภาพถ่าย',
			vi: 'Khu vực chụp ảnh',
		},
		iconKey: 'camera',
		sortingNumber: 3,
		isEventCategory: true,
		isAiRecommendationEnabled: true,
		categoryColorCodes: {
			id: 10,
			paletteNumber: 10,
			sortingNumber: 10,
			colorCode: '#F29AD5',
		},
		_count: {
			facilities: 3,
		},
	},
	{
		id: 4,
		name: {
			ko: '정원',
			en: 'garden',
			zh: '',
			ja: '',
			th: '',
			vi: '',
		},
		iconKey: 'location',
		sortingNumber: 4,
		isEventCategory: false,
		isAiRecommendationEnabled: true,
		categoryColorCodes: {
			id: 4,
			paletteNumber: 4,
			sortingNumber: 4,
			colorCode: '#5DE251',
		},
		_count: {
			facilities: 7,
		},
	},
	{
		id: 3,
		name: {
			ko: '화장실',
			en: 'restroom',
			zh: '',
			ja: '',
			th: '',
			vi: '',
		},
		iconKey: 'toilet',
		sortingNumber: 5,
		isEventCategory: false,
		isAiRecommendationEnabled: true,
		categoryColorCodes: {
			id: 6,
			paletteNumber: 6,
			sortingNumber: 6,
			colorCode: '#72D4EA',
		},
		_count: {
			facilities: 3,
		},
	},
	{
		id: 9,
		name: {
			ko: '주차장',
			en: 'Parking lot',
			zh: '',
			ja: 'ㅈㄱㄹㅇ',
			th: '',
			vi: '',
		},
		iconKey: 'parking',
		sortingNumber: 6,
		isEventCategory: false,
		isAiRecommendationEnabled: false,
		categoryColorCodes: {
			id: 11,
			paletteNumber: 11,
			sortingNumber: 11,
			colorCode: '#965829',
		},
		_count: {
			facilities: 0,
		},
	},
	{
		id: 2,
		name: {
			ko: '음식점',
			en: 'eating house',
			zh: '餐馆',
			ja: '飲食店',
			th: 'ภัตตาคาร',
			vi: 'quán ăn',
		},
		iconKey: 'meat',
		sortingNumber: 7,
		isEventCategory: false,
		isAiRecommendationEnabled: true,
		categoryColorCodes: {
			id: 1,
			paletteNumber: 1,
			sortingNumber: 1,
			colorCode: '#FF5151',
		},
		_count: {
			facilities: 6,
		},
	},
	{
		id: 1,
		name: {
			ko: '카페',
			en: 'cafe',
			zh: '',
			ja: '',
			th: '',
			vi: '',
		},
		iconKey: 'location',
		sortingNumber: 8,
		isEventCategory: false,
		isAiRecommendationEnabled: true,
		categoryColorCodes: {
			id: 2,
			paletteNumber: 2,
			sortingNumber: 2,
			colorCode: '#FF983D',
		},
		_count: {
			facilities: 5,
		},
	},
	{
		id: 23,
		name: {
			ko: '쉼터',
			en: 'Shelter',
			zh: '庇护所',
			ja: 'シェルター',
			th: 'ที่หลบภัย',
			vi: 'Nơi trú ẩn',
		},
		iconKey: 'three',
		sortingNumber: 9,
		isEventCategory: false,
		isAiRecommendationEnabled: false,
		categoryColorCodes: {
			id: 5,
			paletteNumber: 5,
			sortingNumber: 5,
			colorCode: '#23B63C',
		},
		_count: {
			facilities: 2,
		},
	},
	{
		id: 30,
		name: {
			ko: '관광명소',
			en: 'Tourist attractions',
			zh: '旅游景点',
			ja: '観光名所',
			th: 'สถานที่ท่องเที่ยว',
			vi: 'Điểm tham quan du lịch',
		},
		iconKey: 'binoculars',
		sortingNumber: 10,
		isEventCategory: false,
		isAiRecommendationEnabled: true,
		categoryColorCodes: {
			id: 3,
			paletteNumber: 3,
			sortingNumber: 3,
			colorCode: '#F1C71F',
		},
		_count: {
			facilities: 8,
		},
	},
];
